# 本体の設定
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'cjrh/vim-conda'

# ステータスラインの表示内容強化
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'fugitive#head',
      \   'filename': 'LightlineFilename'
      \ },
      \ }

function! LightlineFilename()
  let filename = expand('%:P') !=# '' ? expand('%:P') : '[No Name]'
  return filename
endfunction
'''

# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 111
let g:indentLine_color_gui = '#708090'
'''

# 全角スペースの可視化
[[plugins]]
repo = 'thinca/vim-zenspace'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
command Gadd Gwrite
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
