# 括弧補完
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_event = 'InsertCharPre'

# Ruby, Rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby', 'slim']
hook_source = '''
command Em Emodel
command Ec Econtroller
command Ev Eview
command Eg Emigration
command Es Eschema
command Er Einitializer
'''

# GraphQL
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

# FZF
[[plugins]]
repo = 'junegunn/fzf.vim'
on_map = ['<C-p>']
hook_source = '''
noremap <C-p> :FZF<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
on_source = ['fzf.vim']

# NerdTree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = ['<C-e>']
hook_add = '''
let g:NERDTreeShowHidden = 1
let g:NERDTreeShowBookmarks = 0
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
'''
hook_source = '''
command B Bookmark
noremap <C-e> :NERDTreeToggle<CR>
'''

# コメントアウトライブラリ
[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'CursorMoved'
