# 自動補完機能
[[plugins]]
repo = 'roxma/nvim-yarp'
on_event = 'VimEnter'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertCharPre'

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertCharPre'
hook_source = '''
inoremap <expr><tab> pumvisible() ? "\<C-n>" : neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
imap <C-c>     <Plug>(neosnippet_expand_or_jump)
smap <C-c>     <Plug>(neosnippet_expand_or_jump)
xmap <C-c>     <Plug>(neosnippet_expand_target)
imap <C-c>     <Plug>(neosnippet_expand_or_jump)

let g:neosnippet#snippets_directory = '~/.vim/snippets/'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 10
let g:deoplete#auto_complete_start_length = 2
let g:deoplete#enable_camel_case = 0
let g:deoplete#enable_ignore_case = 0
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#max_list = 10
'''

# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertCharPre'

# Ruby, Rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby', 'slim']
hook_source = '''
command Em Emodel
command Ec Econtroller
command Ev Eview
command Eg Emigration
command Es Eschema
command Er Einitializer
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['haml', 'ruby', 'eruby', 'slim']

# NerdTree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = ['<C-e>']
hook_add = '''
let g:NERDTreeShowHidden = 1
let g:NERDTreeShowBookmarks = 0
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
'''
hook_source = '''
command B Bookmark
noremap <C-e> :NERDTreeToggle<CR>
'''

# カラーテーマ
[[plugins]]
repo = 'crusoexia/vim-monokai'
on_event = 'VimEnter'
hook_post_source = '''
syntax on
colorscheme monokai
set t_Co=256

hi SpecialKey ctermbg=NONE ctermfg=240
hi LineNr ctermbg=NONE ctermfg=248
hi Comment ctermbg=NONE ctermfg=244
hi Normal ctermbg=NONE
'''

# JavaScript
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

# TypeScript
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.tsx']

# GraphQL
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

# Elixir
[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir']

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# FZF
[[plugins]]
repo = 'junegunn/fzf.vim'
on_map = ['<C-p>']
hook_source = '''
noremap <C-p> :FZF<CR>
'''

[[plugins]]
repo = '/usr/local/opt/fzf'
on_source = ['fzf.vim']
