# zplug
source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# theme
zplug "themes/mh", from:"oh-my-zsh", as:"theme"

# ディレクトリのエイリアス
zplug "lib/directories", from:"oh-my-zsh"

# ファイルのタイプによって色をつける
zplug "lib/theme-and-appearance", from:"oh-my-zsh"

# railsコマンド補完
zplug "plugins/rails", from:"oh-my-zsh"
zplug "plugins/rake-fast", from:"oh-my-zsh"

# タイプ補完
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "chrissicool/zsh-256color"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# エディタ設定
export EDITOR=vim

# User configuration
#local用のPATH
export PATH="/usr/local/bin:$PATH"

#TexLive用のPATH
export PATH="$PATH:/usr/local/texlive/2018/bin/x86_64-darwin"

#openssl用のPATH
export PATH=/usr/local/opt/openssl/bin:$PATH

#Ruby用のPATH
eval "$(rbenv init -)"

#Node用のPATH
eval "$(nodenv init -)"

#Python用のPATH
eval "$(pyenv init -)"

## 重複パスを登録しない
typeset -U path cdpath fpath manpath

# ヒストリ(履歴)を保存、数を増やす
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

# 補完候補を一覧表示する
setopt auto_list

# 補完のタブ移動を可能にする
setopt auto_menu
zstyle ':completion:*:default' menu select=1

#URLをちゃんと認識させる
setopt nonomatch

# 日本語ファイル名を表示可能にする
setopt print_eight_bit

# ビープ音の停止
setopt no_beep

# ビープ音の停止(補完時)
setopt nolistbeep

# cd -<tab>で以前移動したディレクトリを表示
setopt auto_pushd

# 同時に起動したzshの間でヒストリを共有する
setopt share_history

# 直前と同じコマンドの場合は履歴に追加しない
setopt hist_ignore_dups

# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups

# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space

# ヒストリに保存するときに余分なスペースを削除する
setopt hist_reduce_blanks

# キーバインディングをemacs風に(-vはvim)
bindkey -e
# bindkey -v

# コマンド自動補正
setopt correct

# 起動時にDownload自動削除
eval "rmtrash ~/Downloads/*"

#auto-fu.zshの設定
source $HOME/.zsh/auto-fu.zsh/auto-fu.zsh
function zle-line-init(){
    auto-fu-init
}
zle -N zle-line-init

# 「-azfu-」を表示させないための記述
zstyle ':auto-fu:var' postdisplay $''

#alias
alias dc="docker-compose"
alias dw="docker-compose run web"
alias oa="open -a"
alias og="oa Google\ Chrome"
alias oh="open https://github.com"
alias rm="rmtrash"
alias g++="g++-8 -std=c++14"
alias ga="git add -A"
alias gc="git commit"
alias gp="git push"
