# zplug
export ZPLUG_HOME=$HOMEBREW_PREFIX/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# theme
zplug "themes/mh", from:"oh-my-zsh", as:"theme"

# ディレクトリのエイリアス
zplug "lib/directories", from:"oh-my-zsh"

# ファイルのタイプによって色をつける
zplug "lib/theme-and-appearance", from:"oh-my-zsh"

# railsコマンド補完
zplug "plugins/rails", from:"oh-my-zsh"
zplug "plugins/rake-fast", from:"oh-my-zsh"

# タイプ補完
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "chrissicool/zsh-256color"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# auto-suggestionsの設定
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
bindkey '^e' autosuggest-execute
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=046,underline"

# エディタ設定
export EDITOR=vim

# User configuration
#local用のPATH
export PATH="/usr/local/bin:$PATH"

# anyenv用の設定
export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"

#openssl用のPATH
export PATH=/usr/local/opt/openssl/bin:$PATH

## 重複パスを登録しない
typeset -U path cdpath fpath manpath

# ヒストリ(履歴)を保存、数を増やす
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

# 補完候補を一覧表示する
setopt auto_list

# 補完のタブ移動を可能にする
setopt auto_menu
zstyle ':completion:*:default' menu select=1

#URLをちゃんと認識させる
setopt nonomatch

# 日本語ファイル名を表示可能にする
setopt print_eight_bit

# ビープ音の停止
setopt no_beep

# ビープ音の停止(補完時)
setopt nolistbeep

# cd -<tab>で以前移動したディレクトリを表示
setopt auto_pushd

# 同時に起動したzshの間でヒストリを共有する
setopt share_history

# 直前と同じコマンドの場合は履歴に追加しない
setopt hist_ignore_dups

# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups

# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space

# ヒストリに保存するときに余分なスペースを削除する
setopt hist_reduce_blanks

# キーバインディングをemacs風に(-vはvim)
bindkey -v

# コマンド自動補正
setopt correct

# trashがインストールされている場合のみ実行
if type trash > /dev/null 2>&1; then
  # 起動時にDownload自動削除
  eval "trash -F ~/Downloads/* > /dev/null 2>&1"
  eval "trash -F ~/Desktop/* > /dev/null 2>&1"

  #alias
  alias rm="trash -F"
fi

#alias
alias dc="docker compose"
alias dcr="docker compose run --rm"
alias dcrs="docker compose run --rm --service-ports"
alias oa="open -a"
alias og="oa Google\ Chrome"
alias oh="open https://github.com"
alias g++="g++-8 -std=c++14"
alias ga="git add -p"
alias gc="git commit -v --no-verify"
alias gp="git push"
alias be="bundle exec"
alias vim="nvim"
alias claude="~/.claude/local/claude"
alias cc="ENABLE_TOOL_SEARCH=true claude --dangerously-skip-permissions"

function gw() {
  branch_name=$1

  if [ -z "$branch_name" ]; then
    echo "Usage: gw <branch-name>"
    return 1
  fi

  if git branch --list | grep -x -q "  $branch_name"; then
    echo "Branch '$branch_name' exists."
    git worktree add .git-worktrees/$branch_name $branch_name
    return 0
  fi

  echo "Branch '$branch_name' does not exist."
  git worktree add -b $branch_name .git-worktrees/$branch_name origin/main
  return 0
}

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(~/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

yes | docker system prune > /dev/null

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
