# GraphQL
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

# Prisma
[[plugins]]
repo = 'prisma/vim-prisma'
on_ft = ['prisma']

# FZF
[[plugins]]
repo = 'junegunn/fzf.vim'
on_map = ['<C-p>']
hook_source = '''
noremap <C-p> :GFiles<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
on_source = ['fzf.vim']

# NerdTree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = ['<C-e>']
hook_add = '''
let g:NERDTreeShowHidden = 1
let g:NERDTreeShowBookmarks = 0
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
'''
hook_source = '''
command B Bookmark
noremap <C-e> :NERDTreeToggle<CR>
'''
