# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

#oh-my-zshのテーマ設定
ZSH_THEME="mh"

#プラグインの設定
plugins=(rails)

# User configuration

# linux brew用のPATH
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

1
#local用のPATH
export PATH="/usr/local/bin:$PATH"

#openssl用のPATH
export PATH=/usr/local/opt/openssl/bin:$PATH

#Ruby用のPATH
eval "$(rbenv init -)"

#URLをちゃんと認識させる
setopt nonomatch

source $ZSH/oh-my-zsh.sh

## 重複パスを登録しない
typeset -U path cdpath fpath manpath

# 日本語ファイル名を表示可能にする
setopt print_eight_bit

# cdなしでディレクトリ移動
setopt auto_cd

# ビープ音の停止
setopt no_beep

# ビープ音の停止(補完時)
setopt nolistbeep

# cd -<tab>で以前移動したディレクトリを表示
setopt auto_pushd

# ヒストリ(履歴)を保存、数を増やす
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

# 同時に起動したzshの間でヒストリを共有する
setopt share_history

# 直前と同じコマンドの場合は履歴に追加しない
setopt hist_ignore_dups

# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups

# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space

# ヒストリに保存するときに余分なスペースを削除する
setopt hist_reduce_blanks

# キーバインディングをemacs風に(-vはvim)
bindkey -e
# bindkey -v

# コマンド自動補正
setopt correct

#auto-fu.zshの設定
source $HOME/.zsh/auto-fu.zsh/auto-fu.zsh
function zle-line-init(){
  auto-fu-init
}
zle -N zle-line-init
# 「-azfu-」を表示させないための記述
zstyle ':auto-fu:var' postdisplay $''

#alias
alias dc="docker-compose"
alias dw="docker-compose run web"
alias rm="rmtrash"
alias gcc="gcc-7"
alias g++="g++-7 -std=c++14"
alias ga="git add -A"
alias gc="git commit"
alias gp="git push"
